from typing import List, Optional, Protocol

from db.models import Chat


class IChatRepo(Protocol):
    async def add_chat(self, chat_id: int, name: str) -> None: ...

    async def get_chat(self, chat_id: int) -> Optional[Chat]: ...

    async def delete_chat(self, chat_id: int) -> None: ...

    async def list_chats(self) -> List[Chat]: ...

    async def find_chats_by_user(self, user_id: int) -> List[Chat]: ...
