async def add_user(user_id: int, username: str) -> None: ...


async def get_user_id_by_telegram_id(telegram_id: int) -> int: ...


async def is_user_exists(user_id: int) -> bool: ...


async def add_user_if_not_exists(telegram_id: int, username: str) -> None: ...
